# Generated by Django 5.2 on 2025-04-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empregado',
            old_name='departamento',
            new_name='cod_departamento',
        ),
    ]
