# Generated by Django 5.2 on 2025-04-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_departamento_empregado_cod_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiais',
            name='solicitacao',
        ),
        migrations.AddField(
            model_name='materiais',
            name='solicitado',
            field=models.BooleanField(default=False),
        ),
    ]
